build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
    ignore:
        - "var"
        - "vendor"
        - "tests"

#setup:
#    composer:
#        action: "install"

test:
#    php_mess_detector:
#        allow_failures: true
#    php_code_sniffer:
#        standard: "PSR2"
#    php_cpd:
#        allow_failures: true
#    php_cs_fixer:
#        args: "--diff --verbose --dry-run"
    php_parallel_lint:
#    security_checker:
#        allowed_warnings: -1

failure:
    email:
        default_mailto_address: farmfan@apes.kz
